name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Build binaries
        run: |
          mkdir -p build
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            build/envgen-darwin-amd64
            build/envgen-darwin-arm64
            build/envgen-linux-amd64
            build/envgen-linux-arm64
            build/envgen-windows-amd64.exe
